TCGA-CRC:
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/TCGA-CRC-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/TCGA-CRC-DX_SLIDE.csv
  feature_dir:
    ctranspath: /lustre/groups/peng/datasets/histology_data/TCGA-CRC/features/Raw/CTransPath
  folds: folds/TCGA-CRC

CPTAC-CRC:
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/coad_cptac_2019_clinical_data.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/coad_cptac_2019_slide.csv
  feature_dir:
    ctranspath: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Raw/CTransPath/
  folds: folds/CPTAC-CRC
